### ISSUE TITLE
请教个烧录问题

### ISSUE THREAD

**Issue by moze-max** [ByteRyze/Hexapod_2#2]
您好，编译好的文件烧录不进板子上是什么原因，应该如何处理？
虽然您在readme文件中提出要做一些更改，但是当我进入项目的时候发现已经被您改过了，所以我没有做什么改变，编译后直接开始烧录。
我试过在STM32cubeProgrammer上试图烧录，尝试过hex文件与avf文件，也尝试过100,125hz的频率（因为pro上没有120hz的频率），32\16\8位数据也都尝试过，地址address 0x800000和0x900000也都尝试过，均无法正常烧录，并且出现下面的报错:
  11:21:14 : Error: failed to download Segment[0]
  11:21:14 : Error: failed to download the File
我也试过使用开发板厂商的烧录工具，同样出现了这样的报错，但是当我试图向板子烧录一个空项目以证明板子是否损坏的时候，烧录却成功了，这说明板子应该没有问题。
我也检查过avf与hex文件的大小，均没有超过128KB，同时，STM32cubemax也都更新到最新版，编译过程没有报错，只是出现了两个定义未使用的警告。
希望能得到您的解答。

**Comment by BestRyze** [comment]
程序是烧写在外部flash的，建议您在keil中添加核心板的官方外部flash烧写程序，再进行烧录

**Comment by moze-max** [comment]
感谢您的回答，我之前在烧录的时候用错了烧录程序，导致烧录失败。
